import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { parseLeague } from './league';
import { displayTime, mergeLeague, resolvePlayer, validateStandings } from './model';
import { audit, load } from './store';
import { galleryImageURL } from '../../src/lib/gallery-images';

const root=process.cwd(), data=load(root);
const html=fs.readFileSync('scripts/content/fixtures/league.html','utf8');
const parsed=parseLeague(html,data.settings,'2026/27','2026-10-03',data.standings.rows.map(r=>r.team));
assert.equal(parsed.standings.rows.length,8);
assert.equal(parsed.matches.length,3);
assert.equal(parsed.standings.rows.filter(r=>r.isHighlighted).length,1);
assert.throws(()=>parseLeague('<html>Service unavailable</html>',data.settings,'2026/27','2026-10-03',[]));
assert.throws(()=>parseLeague(html.replaceAll('standing-table__points','changed'),data.settings,'2026/27','2026-10-03',[]));
assert.throws(()=>validateStandings({...parsed.standings,rows:parsed.standings.rows.map((r,i)=>i===0?{...r,points:123}:r)}));
const merged=mergeLeague(data.matches,parsed.matches,'2026/27',Date.parse('2026-10-03T12:00Z'));
assert.deepEqual(merged.data.played.find(m=>m.id===6612),data.matches.played.find(m=>m.id===6612));
assert.deepEqual(merged.data.played.find(m=>m.id===6676)?.details,data.matches.played.find(m=>m.id===6676)?.details);
assert.deepEqual(mergeLeague(merged.data,parsed.matches,'2026/27',Date.parse('2026-10-03T12:00Z')).data,merged.data);
const confirmed=data.matches.played.find(m=>m.id===6612)!;
assert.equal(mergeLeague(data.matches,[{...confirmed,homeScore:9}],'2026/27',0).conflicts.length,1);
assert.equal(resolvePlayer('Gašper Martič',data.players,{}),'GM');
assert.equal(resolvePlayer('gasper',data.players,{gasper:'GM'}),'GM');
assert.throws(()=>resolvePlayer('Porenta',data.players,{}),/ambiguous/);
assert.equal(displayTime('2026-12-01T08:00:00+01:00'),'08:00');
assert.equal(displayTime('2026-07-01T08:00:00+02:00'),'08:00');
assert.equal(galleryImageURL('/images/a.jpg',640,'thumbnail',false),'/images/a.jpg');
assert.match(galleryImageURL('/images/a.jpg',640,'thumbnail',true),/fit=cover,width=640,height=640/);
assert.equal(galleryImageURL('https://example.com/a.jpg',640,'thumbnail',true),'https://example.com/a.jpg');
assert.equal(audit(root,data).errors.length,0);

const sandbox=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'lisjaki-content-integration-')));
try {
  fs.cpSync(path.join(root,'src/data'),path.join(sandbox,'src/data'),{recursive:true});
  fs.writeFileSync(path.join(sandbox,'wrangler.jsonc'),'{}');
  // Only referenced files are needed; symlink-free byte copies preserve the audit boundary.
  const refs=new Set([...data.gallery.featured.map(i=>i.src),...data.gallery.events.flatMap(g=>[g.coverImage,...g.images.map(i=>i.src)]),...data.news.map(n=>n.image)].filter(s=>s.startsWith('/')));
  for(const url of refs){const file=path.join(sandbox,'public',url);fs.mkdirSync(path.dirname(file),{recursive:true});fs.copyFileSync(path.join(root,'public',url),file);}
  const cli=process.argv[2];
  const run=(args:string[],success=true)=>{const r=spawnSync(process.execPath,[cli,...args,'--root',sandbox],{encoding:'utf8'});assert.equal(r.status,success?0:1,r.stdout+r.stderr);return r;};
  const input=(name:string,value:unknown)=>{const file=path.join(sandbox,name+'.json');fs.writeFileSync(file,JSON.stringify(value));return file;};
  const fixture=data.matches.upcoming[0];
  const details={home:{lineup:['Gašper Martič','Blaž Logonder','Tomaž Hribernik'],goalscorers:[{player:'Blaž Logonder'}]},away:{lineup:[],goalscorers:[]}};
  const update=input('match',{id:fixture.id,homeScore:1,awayScore:0,details,absent:['Tomaž Hribernik']});
  const before=fs.readFileSync(path.join(sandbox,'src/data/content/matches.json'));
  run(['match','upsert',update,'--dry-run']);assert.deepEqual(fs.readFileSync(path.join(sandbox,'src/data/content/matches.json')),before);
  run(['match','upsert',update]);const once=fs.readFileSync(path.join(sandbox,'src/data/content/matches.json'));
  assert(!load(sandbox).matches.upcoming.some(m=>m.id===fixture.id));
  assert.deepEqual(load(sandbox).matches.played.find(m=>m.id===fixture.id)?.details?.home.lineup,['GM','BL']);
  run(['match','upsert',update]);assert.deepEqual(fs.readFileSync(path.join(sandbox,'src/data/content/matches.json')),once);
  const bad=input('bad',{id:fixture.id,homeScore:0,awayScore:0,details});run(['match','upsert',bad],false);
  assert.deepEqual(fs.readFileSync(path.join(sandbox,'src/data/content/matches.json')),once);
  const batch=input('batch',{actions:[{command:'roster upsert',input:{initials:'GM',number:99}},{command:'match upsert',input:{id:fixture.id,homeScore:-1}}]});
  const roster=fs.readFileSync(path.join(sandbox,'src/data/content/players.json'));run(['batch',batch],false);assert.deepEqual(fs.readFileSync(path.join(sandbox,'src/data/content/players.json')),roster);
  const source=path.join(sandbox,'source');fs.mkdirSync(source);fs.copyFileSync(path.join(root,'public',data.gallery.featured[0].src),path.join(source,'photo.jpg'));
  const importFile=input('gallery',{slug:'test-event',title:'Test event',date:'2026-10-03',source,cover:'photo.jpg'});
  run(['gallery','import',importFile]);const galleryOnce=fs.readFileSync(path.join(sandbox,'src/data/content/gallery.json'));run(['gallery','import',importFile]);assert.deepEqual(fs.readFileSync(path.join(sandbox,'src/data/content/gallery.json')),galleryOnce);
  const album=load(sandbox).gallery.events.find(g=>g.slug==='test-event')!;
  assert(fs.existsSync(path.join(source,'photo.jpg')));assert.match(album.images[0].src,/photo-[a-f0-9]{16}\.jpg$/);
  const articleFile=input('article',{slug:'test-event',title:'Test event',excerpt:'Known facts only.',publishedAt:'2026-10-03',image:album.coverImage,content:'# Test event\n\nKnown facts only.'});
  run(['article','add',articleFile]);assert.equal(load(sandbox).news.find(n=>n.slug==='test-event')?.gallerySlug,'test-event');
  const coverInput=input('cover',{slug:'standalone-report',title:'Standalone',excerpt:'Supplied photo.',publishedAt:'2026-10-03',imageSource:path.join(source,'photo.jpg'),content:'# Standalone\n\nSupplied photo.'});
  run(['article','add',coverInput]);assert.match(load(sandbox).news.find(n=>n.slug==='standalone-report')!.image,/^\/images\/news\/photo-/);
  assert(fs.existsSync(path.join(source,'photo.jpg')));
  const mediaInput=input('media',{source:path.join(source,'photo.jpg')});run(['media','import',mediaInput,'--dry-run']);
  const rosterInput=input('roster',{initials:'JJES',number:50,aliases:['Jesenko']});run(['roster','upsert',rosterInput]);assert.equal(load(sandbox).settings.playerAliases.Jesenko,'JJES');
  run(['roster','upsert',input('conflicting-alias',{initials:'GM',aliases:['Jan Jesenko']})],false);
  const articleOnce=fs.readFileSync(path.join(sandbox,'src/data/content/news.json'));run(['article','add',articleFile]);assert.deepEqual(fs.readFileSync(path.join(sandbox,'src/data/content/news.json')),articleOnce);
  const rawHTML=input('html',{...JSON.parse(fs.readFileSync(articleFile,'utf8')),content:'<script>alert(1)</script>'});run(['article','add',rawHTML],false);
  assert.deepEqual(fs.readFileSync(path.join(sandbox,'src/data/content/news.json')),articleOnce);
  const reorder=input('reorder',{slug:'test-event',order:['not-there']});run(['gallery','reorder',reorder],false);
  const escape=input('escape',{...JSON.parse(fs.readFileSync(importFile,'utf8')),slug:'../../escape'});run(['gallery','import',escape],false);
  const season=input('season',{actions:[{command:'season set',input:{season:'2027/28',source:'https://sport-radovljica.si/tekmovanje/new/',group:'C'}}]});run(['batch',season]);assert.equal(load(sandbox).settings.activeSeason,'2027/28');assert(load(sandbox).matches.played.length>0);
} finally {fs.rmSync(sandbox,{recursive:true,force:true});}
console.log('Content tests passed: league parsing, protected corrections, name resolution, DST, batch rollback, dry runs, repeat imports, galleries, articles, path boundaries, season rollover.');
